### ISSUE TITLE
Development server not working

### ISSUE THREAD

**Issue by Tartsi** [Wincewind/ohtu-s23-miniprojekti#40]
Development server opens correctly but cannot find the correct path.

"Not Found 
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

Tried with 2 different Windows computers, a full reset (all the way from cloning) and with both invoke start and "flask --app src/app.py run" (both throw the same error).

Unsure what is causing this at the moment... 🤷‍♂️

**Comment by Wincewind** [comment]
In which branch is this occuring? I'm having no issues with main on Windows.

**Comment by Tartsi** [comment]
Branch #39, which was the main at the time. Currently on phone so cannot test.

**Comment by Tartsi** [comment]
Still not working locally on my Windows-computers, live-version (Fly.io) functioning properly however.

**Comment by Tartsi** [comment]
![Näyttökuva 2023-12-03 210939](https://github.com/Wincewind/ohtu-s23-miniprojekti/assets/62020899/50f4044d-b5d2-42c0-a6d4-4ff36e4b74d8)
![Näyttökuva 2023-12-03 211049](https://github.com/Wincewind/ohtu-s23-miniprojekti/assets/62020899/ae015b0e-9b16-45af-8429-abd3f5aceb2c)

**Comment by Tartsi** [comment]
Running command "flask --app src/app.py run --debug" does not change output in anyway, therefore I do not think the problem is Flask-related.

**Comment by Tartsi** [comment]
Issue resolved.

Solution: My build-folder had apparently been deleted/removed at some point during moving between different branches. Did not realize until it was pointed out for me, props to @Wincewind!
