### ISSUE TITLE
Duplicate ID issue

### ISSUE THREAD

**Issue by yogajones** [Wincewind/ohtu-s23-miniprojekti#51]
In a call with @PlatinumFoxTail, we discovered the following issue:

- /delete_references route receives a list of id numbers from the web form.
- The list could be [1] in a scenario where only one book _or_ one article is saved to the database. Since both reference objects have their separate tables, their respective ID numbers are not linked in any way.
- How do we know if we should remove a book with ID 1 or an article with ID 1?
- If we want to delete a list of both articles and books (e.g. [1,2,3,3,4,5,5,6,6]), mayhem is currently inevitable.

Possible solutions:
- use one table 'References' with a field for reference type: book or article.
- pass ID's as tuples (e.g. (1, "book"), (1, "article")) - this seems quite cowboy/gumfix

Other ideas?

**Comment by Tartsi** [comment]
All problems can be solved with a single radio button / dropdown menu.

We then check on Routes.py /delete, /add - methods if a button is selected or not and this with a simple if/else chooses the correct pathway to delete a reference from either books table or articles table. Or in dropdown menus situation we check which one is selected 🤷‍♂️.

This limits the amount of changes that need to be made to minimum in my opinion.

**Comment by ismomehdi** [comment]
Replied in Discord:

> Jos lisätään toi dropdown, minkä @Tartsi mainitsi, niin imo ois ehkä iisein, et ois kirjoille ja artikkeleille erikseen omat routet (get_all_books , delete_books, get_all_articles , delete_articles tjsp).
> 
> Muuten, jos ne kaikki haetaan samasta routesta, niin frontendin puolella täytyy tehä joku viritelmä mikä osais päätellä millon mikäkin on kirja tai artikkeli. Ja toi menee ehkä vähän turhan monimutkaseks.
> 
> Ehkä täs vaihees ehdottaisin kans, et se frontend referenssilista voiski näyttää vaan sen dropdownin perusteella joko vaan kirjoja tai sit vaan artikkeleita. UX puolesta ei ehkä paras ratkasu, mut alkaa vähän aika loppuu kesken, ni toi ois ehkä nopein toteuttaa 😅
> 
> Onks muilla viel tunteja jäljellä?
>
