### ISSUE TITLE
Frontend not showing error messages

### ISSUE THREAD

**Issue by Tartsi** [Wincewind/ohtu-s23-miniprojekti#53]
![image](https://github.com/Wincewind/ohtu-s23-miniprojekti/assets/62020899/b38ff89b-38d2-4d1b-9449-5807cf0cf8e4)
I am getting this kind of error on console constantly.

![image](https://github.com/Wincewind/ohtu-s23-miniprojekti/assets/62020899/c936e07a-5800-4ffb-b07a-d3e63d15459b)

There is the problem. The alert is not returning the proper error-message from Routes.py /add_references-method.
Tried fixing this myself but did not succeed. @ismomehdi Hopefully can fix this.

**Comment by Wincewind** [comment]
Did some debugging and the response handling in referenceService.js should look like this:

```
if (!response.ok) {
            const responseData = await response.json();
            throw new Error(JSON.stringify(responseData.message));
        }
```

**Comment by ismomehdi** [comment]
Thanks @Wincewind !
