### ISSUE TITLE
Book table, publisher_address column needed?

### ISSUE THREAD

**Issue by PlatinumFoxTail** [Wincewind/ohtu-s23-miniprojekti#8]
En tiedä @yogajones jos tämä on oikea kanava kysyä kysymyksiä, mutta pohdin tarvitaanko Books tauluun sarake publisher_address? Viittaan tähän:

https://github.com/Wincewind/ohtu-s23-miniprojekti/blob/5fcbfb0e4dbe3e15f209bcd7190271b2d0d144ad/schema.sql#L12

Tämän pohjalta saan kuvan, ettei tarvitse https://ohjelmistotuotanto-hy.github.io/speksi/

**Comment by Wincewind** [comment]
Might not be needed, but shouldn't (probably) cause problems. What we did notice was the extra comma after "publication_year INT NOT NULL," which we fixed at least in flask_view branch.

**Comment by PlatinumFoxTail** [comment]
OK, jatketaan tällä.
